// This file is generated by npm run build:icons

export type IconName =
	| 'bell'
	| 'footprints'
	| 'heart'
	| 'home'
	| 'magnifying-glass'
	| 'newspaper'
	| 'person'
	| 'shirt'
	| 'shopping-bag'
	| 'shopping-cart'
	| 'ticket'
